name: Test Node.js

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Build and test
      run: |
          npm i
          npm test
